version: '3.8'

services:
  php72:
    build:
      context: ./php72
      dockerfile: Dockerfile
    container_name: php72-env
    volumes:
      - ../src:/app/src
      - ../output:/app/output
    working_dir: /app
    tty: true
    stdin_open: true
    networks:
      - php-network

  php84:
    build:
      context: ./php84
      dockerfile: Dockerfile
    container_name: php84-env
    volumes:
      - ../src:/app/src
      - ../output:/app/output
    working_dir: /app
    tty: true
    stdin_open: true
    networks:
      - php-network

networks:
  php-network:
    driver: bridge

